### ISSUE TITLE
New Icon Sets

### ISSUE THREAD

**Issue by swapnilsarwe** [iconify/collections-json#13]
Hello,

Is there any way i can contribute to add to the collection?
Or I should just suggest the icon with the repository and the details and you will get it added eventually as per your availability?

Some icon sets:
https://github.com/Make-Lemonade/iconicicons
https://github.com/nagoshiashumari/rpg-awesome-raw

**Comment by cyberalien** [comment]
Contributing is impossible because repository is maintained automatically, so every addition must be done to icon update script, not repository. However, suggestions of good icon sets are very welcome!

As for those two icon sets:

First icon set is very good. However it is missing a valid open source license, which is a requirement for icon set to be added to Iconify. I'll open an issue at that repository.

Second icon set is a set of images that has not been maintained for 6 years. They have weird grid of 613x613 pixels. It is not a good set.

**Comment by swapnilsarwe** [comment]
> Contributing is impossible because repository is maintained automatically, so every addition must be done to icon update script, not repository. However, suggestions of good icon sets are very welcome!

Understood the point, I thought that automated script might be open sourced and may be I can contribute few more sets to it. 

We have a package in laravel called [blade-icons](https://github.com/blade-ui-kit/blade-icons) which is the base package and people can build there icon packages on top of it. There are lot of contributions who have contributed many icon sets with little tweaking and cleanup. I was wondering all that process can be used to expand iconify its icon sets.

Anyways I will list down few of the icon-sets suggestions which are listed in blade-icons which are missing in iconify.

**Comment by cyberalien** [comment]
Sets available with Blade Icons do include few sets that I didn't see before that are open source and well designed. Thank you for linking it!

In PHP this icon sets repository is available as `iconify/json`: https://packagist.org/packages/iconify/json which can probably be used to add Iconify sets with Blade UI. Tools for converting icons are available for PHP here: https://github.com/iconify/json-tools.php They haven't been maintained for a while, but should work fine.

As for update script, it is not available, but code it uses to convert stuff is available in Iconify Tools: https://github.com/iconify/tools All import and export functions are available in tools package, which was originally written specifically for icon sets update script.

**Comment by swapnilsarwe** [comment]
> In PHP this icon sets repository is available as `iconify/json`: https://packagist.org/packages/iconify/json which can probably be used to add Iconify sets with Blade UI.

I am giving that a thought, rather than maintaining similar sets at 2 places, I can make use of iconify php tool to integrate iconify icon sets with blade ui. With that number of sets would be readily available in blade ui and updating sets would be just iconify responsibility.

Will keep you posted on the progress. Closing this issue.

**Comment by cyberalien** [comment]
Thanks for linking Blade Icons project, I've added about 10 icon sets from there that I didn't know about!

There are few issues with Blade Icons though:
- Blade Fork Awesome is pretty much unusable. Just look at any SVG and you'll see why. Whole FontAwesome project is usable only as font and was designed that way.
- Pepicons doesn't have license. You've published it as MIT, but original icons are missing license. I've opened an issue at author's repository, so hopefully it can be fixed soon.
- Country Flags icon set has few icons that rely on rare fonts, so they don't render correctly.

**Comment by swapnilsarwe** [comment]
Hey @cyberalien ,

These are few more icon collections compilation i came across, not sure how helpful it would be for you. Thought of sharing it with you anyways.

- https://undesign.learn.uno/icons/
- https://designresources.dev/icons/
