### ISSUE TITLE
Boxicons not up to date

### ISSUE THREAD

**Issue by bennetfabian** [iconify/collections-json#25]
The last commit to this repo was 2 days ago while the last commit adding new icons to Boxicons repo was 23 hours ago.

**Comment by cyberalien** [comment]
That's correct. Update isn't instant, currently script that updates icon sets is ran 3 times a week. Last run was about 1.5 days ago, next one is scheduled for Monday morning (European time).

I do want to change it to continuous updates, but it will take some time to implement.

**Comment by bennetfabian** [comment]
Okay, that's understandable. Could you merge #26 then? It corrects the information in README.

**Comment by cyberalien** [comment]
Thanks! Merged.
