### ISSUE TITLE
Add Charm Icons

### ISSUE THREAD

**Issue by jaynewey** [iconify/collections-json#28]
Hi,

I've only recently discovered Iconify but I'm a fan!

I wonder (without bigging myself up too much) if my icon set [Charm](https://github.com/jaynewey/charm-icons) could be added.

<div align="center">
<img src="https://raw.githubusercontent.com/jaynewey/charm-icons/3f992040b730ee923445373b63c3cdad291de3a0/docs/img/splash.svg">
</div>

It is open source and licensed under MIT.

Thanks!

**Comment by cyberalien** [comment]
Thanks.

Sure, it can be added. Your icon set looks good.

Each icon set has its own prefix. Which one do you prefer: `charm` or `charm-icons` or something else?

**Comment by jaynewey** [comment]
`charm` sounds great.

and thanks!

**Comment by cyberalien** [comment]
Added
