### ISSUE TITLE
noto.json - baseball

### ISSUE THREAD

**Issue by SavaSebastian** [iconify/collections-json#5]
Hi !

noto:baseball icon doesn't work.

Thanks !

**Comment by cyberalien** [comment]
Looks fine to me. Where exactly it doesn't work?

**Comment by SavaSebastian** [comment]
Sorry, my mistake. I tried with 0 0 viewBox.

**Comment by cyberalien** [comment]
Oh I see, that icon does have weird left and top offset 😀
