### ISSUE TITLE
Request to add Heroicons and Zondicons

### ISSUE THREAD

**Issue by utkarshkukreti** [iconify/collections-json#7]
(Not sure if this is the right place to ask but I saw some requests here in closed issues so I'm posting here.)

I'd like to have these two icon sets:

1. https://github.com/refactoringui/heroicons (MIT)
2. https://github.com/dukestreetstudio/zondicons (https://www.zondicons.com/; MIT)

I'd write the crawler but I can't find the scripts you wrote to crawl all other icon sets. Are they in some other repo?

**Comment by cyberalien** [comment]
Thanks for opening this issue. Those icons sets look very well designed and they are open source, so I'll definitely add them!

Crawler script is not public. However it is based on Iconify Tools package, so everything needed to convert icon sets is available.

**Comment by utkarshkukreti** [comment]
Thank you for considering. :)

**Comment by cyberalien** [comment]
Added both icon sets.

Really good icon sets, very well designed and easy to work with! I wish more icons sets were designed like that.

**Comment by utkarshkukreti** [comment]
Thanks!

> easy to work with!

Yep, the SVG code they have is pretty much perfect for copy-pasting and using. It uses `currentColor` and is already run through svgo.
