### ISSUE TITLE
Request to add IBM Carbon Design Icons

### ISSUE THREAD

**Issue by mrsideshowjack** [iconify/collections-json#8]
Saw there was a similar closed issue, thought you might like to include IBM's Carbon Design Icons, they have Apache License 2.0. All the svg's are available through the github repo

Library Page: https://www.carbondesignsystem.com/guidelines/icons/library/

Github Repo: https://github.com/carbon-design-system/carbon/tree/master/packages/icons

**Comment by cyberalien** [comment]
That's a great icon set, but unfortunately it is not complete.

I've opened their icon set in Sketch, there are plenty of 16x16, 20x20 and 24x24 icons. Yet in repository there are:
- 73 16x16 icons
- 11 20x20 icons
- 10 24x24 icons

The only consistent icon set is 32x32.

I'll see what can be done about that. For now it looks like only 32x32 set is up to date and can be added.

**Comment by cyberalien** [comment]
I went through their build process. It appears smaller size icons are mostly generated by scaling down 32x32 icons, except for few icons I've mentioned above. So in essence it is a 32x32 set.

Add them to icon sets.
